var formNewUser = '';
formNewUser += '<div id="fixture"><div id="fb-root"></div><a href="https://www.stitchfix.com/login?utm_campaign=68ba126472fa2d9a8bb75a848dbd29cd&amp;utm_source=ampush&amp;utm_medium=other" class="login btn btn-white">Sign In</a><form method="post" accept-charset="UTF-8" action="https://www.stitchfix.com/?utm_campaign=68ba126472fa2d9a8bb75a848dbd29cd&amp;utm_source=ampush&amp;utm_medium=other" id="new_user" data-init-blur-form-validation="true" data-init-batch-form-validation="true" novalidate="novalidate" class="">';
formNewUser += '<input type="hidden" value="✓" name="utf8">';
formNewUser += '<input type="hidden" value="N6XNgkKhiVmZndbJ6BaaajtZsvdaAsj/STamlcwBZl1UtzE0615aJMabpItASAcvH+rJ4Z+BbS7O8xC76FESSg==" name="authenticity_token">';
formNewUser += '<div class="sign-in-form fb-login-c" style="">';
formNewUser += '<div>';
formNewUser += '<ul>';
formNewUser += '<li>';
formNewUser += '<div>';
formNewUser+='<a href="javascript:void(0)" id="fb-button" data-controller-path="/linked_accounts/facebook/info" data-controller-action="GET" onclick="checkLoginState(this, new_user)">';
formNewUser += '<div id="facebook_logo">';
formNewUser += '<span class="facebook-f-logo"><img class="center-facebook-f-logo" src="images/facebook_icon.png"></span>';
formNewUser += '</div>';
formNewUser += '<div class="facebook-text-box" id="facebook_signup">SIGN UP WITH FACEBOOK</div>';
formNewUser += '</a>';
formNewUser += '</div>';
formNewUser += '</li>';
formNewUser += '</ul>';
formNewUser += '<div class="line-separator"> OR </div>';
formNewUser += '</div>';
formNewUser += '</div>';
formNewUser += '<div class="sign-in-form fb-login-d" style="display:none;">';
formNewUser += '<div data-validate="presence" class="form-group">';
formNewUser += '<ul>';
formNewUser+='<li><a class="linkFB" data-controller-path="/linked_accounts/facebook/info" data-controller-action="GET" href="javascript:void(0)" onclick="checkLoginState(this, new_user)"><i aria-hidden="true" class="fa fa-facebook"></i><span>Continue with Facebook</span></a></li>';
formNewUser += '</ul>';
formNewUser += '<div class="midStrip"><span>OR</span></div>';
formNewUser += '</div>';
formNewUser += '</div>';
formNewUser += '<div data-validate="presence" class="form-group">';
formNewUser += '<label for="user_first_name" class="control-label">First Name</label>';
formNewUser += '<input type="text" id="user_first_name" name="user[first_name]" size="30" class="form-control input-lg" maxlength="30">';
formNewUser += '<div style="color:#ff5c61;font-size:11pt" class="error-msg"><em><span>This is a required field</span></em></div></div>';
formNewUser += '<div data-validate="presence" class="form-group">';
formNewUser += '<label for="user_last_name" class="control-label">Last Name</label>';
formNewUser += '<input type="text" id="user_last_name" name="user[last_name]" size="30" class="form-control input-lg" maxlength="30">';
formNewUser += '</div>';
formNewUser += '<div data-validate="presence,email,emailUniqueness, emailValidTopLevelDomain, emailRareTopLevelDomain" class="form-group">';
formNewUser += '<label for="user_email" class="control-label">Email</label>';
formNewUser += '<input type="email" id="user_email" name="user[email]" size="75" class="form-control input-lg" maxlength="75">';
formNewUser += '</div>';
formNewUser += '<div data-validate="presence,zip" class="form-group" style="display: none;">';
formNewUser += '<label for="user_client_attributes_shipping_postcode" class="control-label">Zip Code</label>';
formNewUser += '<input type="hidden" id="user_client_attributes_shipping_postcode" name="user[client_attributes][shipping_postcode]" size="10" maxlength="10" class="form-control input-lg" value="94107">';
formNewUser += '<p class="instructional-note  inline-note">At this time we ship only to U.S. mailing addresses.</p>';
formNewUser += '</div>';
formNewUser += '<div data-validate="presence" class="form-group">';
formNewUser += '<label for="user_client_attributes_scalar_attributes_attributes_dress_generic_size_id" class="control-label"> Dress Size </label>';
formNewUser += '<div data-toggle="buttons" class="btn-group">';
formNewUser += '<label class="btn btn-default">';
formNewUser += '<input type="radio" class="form-control rbtn-scale" value="37" id="user_client_attributes_scalar_attributes_attributes_dress_generic_size_id_37" name="user[client_attributes][scalar_attributes_attributes][dress_generic_size_id]">';
formNewUser += 'XS</label>';
formNewUser += '<label class="btn btn-default">';
formNewUser += '<input type="radio" class="form-control rbtn-scale" value="38" id="user_client_attributes_scalar_attributes_attributes_dress_generic_size_id_38" name="user[client_attributes][scalar_attributes_attributes][dress_generic_size_id]">';
formNewUser += 'S</label>';
formNewUser += '<label class="btn btn-default">';
formNewUser += '<input type="radio" class="form-control rbtn-scale" value="39" id="user_client_attributes_scalar_attributes_attributes_dress_generic_size_id_39" name="user[client_attributes][scalar_attributes_attributes][dress_generic_size_id]">';
formNewUser += 'M</label>';
formNewUser += '<label class="btn btn-default">';
formNewUser += '<input type="radio" class="form-control rbtn-scale" value="40" id="user_client_attributes_scalar_attributes_attributes_dress_generic_size_id_40" name="user[client_attributes][scalar_attributes_attributes][dress_generic_size_id]">';
formNewUser += 'L</label>';
formNewUser += '<label class="btn btn-default">';
formNewUser += '<input type="radio" class="form-control rbtn-scale" value="41" id="user_client_attributes_scalar_attributes_attributes_dress_generic_size_id_41" name="user[client_attributes][scalar_attributes_attributes][dress_generic_size_id]">';
formNewUser += 'XL</label>';
formNewUser += '</div>';
formNewUser += '<p class="instructional-note hidden-xs">Need sizing help? Consult our <a class="size-chart" data-target="#sizeChart-pop" data-toggle="modal" href="#">Size Chart »</a></p>';
formNewUser += '<p class="instructional-note">We carry sizes 0&ndash;14 (XS&ndash;XL),';
formNewUser += 'as well as maternity and petite&nbsp;clothing. </p>';
formNewUser += '</div>';
formNewUser += '<div class="form-group submission">';
formNewUser += '<p class="instructional-note">By signing up you accept the';
formNewUser += '<a href="https://www.stitchfix.com/terms?utm_campaign=68ba126472fa2d9a8bb75a848dbd29cd&amp;utm_source=ampush&amp;utm_medium=other">terms and conditions</a> of Stitch&nbsp;Fix.</p>';
formNewUser += '<input type="submit" data-disable-with="Signing up..." class="btn btn-red btn-lg submit" value="Take Your Style Quiz" name="commit">';
formNewUser += '<div class="help-block">Already a member? <a href="https://www.stitchfix.com/login?utm_campaign=68ba126472fa2d9a8bb75a848dbd29cd&amp;utm_source=ampush&amp;utm_medium=other">Sign In »</a></div>';
formNewUser += '<div class="registration-opt-in">';
formNewUser += '<div class="email-opt-in">';
formNewUser += '<div class="checkbox small">';
formNewUser += '<input type="hidden" value="0" name="user[email_opt_in]">';
formNewUser += '<input type="checkbox" id="user_email_opt_in" name="user[email_opt_in]" checked="checked" value="1">';
formNewUser += '<label for="user_email_opt_in" class="control-label">Id like to receive exclusive news, styling tips and more</label>';
formNewUser += '</div>';
formNewUser += '</div>';
formNewUser += '</div>';
formNewUser += '</div>';
formNewUser += '</form></div>';


var formNewUserPop = '';

formNewUserPop += '<div id="fb-root"></div><div data-validate="presence" class="form-group">';
formNewUserPop += '<div data-toggle="buttons" class="btn-group">';
formNewUserPop += '<label class="btn btn-default bannersize">';
formNewUserPop += '<input type="radio" class="form-control rbtn-scale-pop" value="37" id="user_client_attributes_scalar_attributes_attributes_dress_generic_size_id_37" name="user[client_attributes][scalar_attributes_attributes][dress_generic_size_id]">';
formNewUserPop += 'XS</label>';
formNewUserPop += '<label class="btn btn-default bannersize">';
formNewUserPop += '<input type="radio" class="form-control rbtn-scale-pop" value="38" id="user_client_attributes_scalar_attributes_attributes_dress_generic_size_id_38" name="user[client_attributes][scalar_attributes_attributes][dress_generic_size_id]">';
formNewUserPop += 'S</label>';
formNewUserPop += '<label class="btn btn-default bannersize">';
formNewUserPop += '<input type="radio" class="form-control rbtn-scale-pop" value="39" id="user_client_attributes_scalar_attributes_attributes_dress_generic_size_id_39" name="user[client_attributes][scalar_attributes_attributes][dress_generic_size_id]">';
formNewUserPop += 'M</label>';
formNewUserPop += '<label class="btn btn-default bannersize">';
formNewUserPop += '  <input type="radio" class="form-control rbtn-scale-pop" value="40" id="user_client_attributes_scalar_attributes_attributes_dress_generic_size_id_40" name="user[client_attributes][scalar_attributes_attributes][dress_generic_size_id]">';
formNewUserPop += 'L</label>';
formNewUserPop += '<label class="btn btn-default bannersize">';
formNewUserPop += '<input type="radio" class="form-control rbtn-scale-pop" value="41" id="user_client_attributes_scalar_attributes_attributes_dress_generic_size_id_41" name="user[client_attributes][scalar_attributes_attributes][dress_generic_size_id]">';
formNewUserPop += 'XL</label>';
formNewUserPop += '</div>';
formNewUserPop += '<p class="instructional-note hidden-xs">Need sizing help? Consult our <a class="size-chart" data-target="#sizeChart-pop" data-toggle="modal" href="#">Size Chart »</a></p>';
formNewUserPop += '</div>';
formNewUserPop += '<form method="post" accept-charset="UTF-8" action="https://www.stitchfix.com/?utm_campaign=68ba126472fa2d9a8bb75a848dbd29cd&amp;utm_source=ampush&amp;utm_medium=other" id="new_user_pop" data-init-blur-form-validation="true" data-init-batch-form-validation="true" novalidate="novalidate" class="">';
formNewUserPop += '<input type="hidden" value="✓" name="utf8">';
formNewUserPop += '<input type="hidden" value="37" name="user[client_attributes][scalar_attributes_attributes][dress_generic_size_id]" id="popupsize">';
formNewUserPop += '<input type="hidden" value="N6XNgkKhiVmZndbJ6BaaajtZsvdaAsj/STamlcwBZl1UtzE0615aJMabpItASAcvH+rJ4Z+BbS7O8xC76FESSg==" name="authenticity_token">';
formNewUserPop += '<!--input value="Womens" type="hidden" name="user[business_line]" id="user_business_line" />';
formNewUserPop += '<input type="hidden" name="user[fb_oauth_token]" id="user_fb_oauth_token" /-->';
formNewUserPop += '<div class="sign-in-form fb-login-c" style="">';
formNewUserPop += '<div>';
formNewUserPop += '<ul>';
formNewUserPop += '<li><div>';
//formNewUserPop +='<a href="javascript:void(0)" id="fb-button" data-controller-path="/linked_accounts/facebook/info" data-controller-action="GET" onclick="checkLoginState(this, 'new_user_pop')">';
formNewUserPop += '<div id="facebook_logo">';
//formNewUserPop +='formNewUserPop +='<span class="facebook-f-logo"><img class="center-facebook-f-logo" src="images/facebook_icon.png"></span>';
formNewUserPop += '</div>';
formNewUserPop += '<div class="facebook-text-box" id="facebook_signup">SIGN UP WITH FACEBOOK</div>';
formNewUserPop += '</a>';
formNewUserPop += '</div>';
formNewUserPop += '</li>';
formNewUserPop += '</ul>';
formNewUserPop += '<div class="line-separator"> OR </div>';
formNewUserPop += '</div>';
formNewUserPop += '</div>';
formNewUserPop += '<div class="sign-in-form fb-login-d" style="display:none;">';
formNewUserPop += '<div data-validate="presence" class="form-group">';
formNewUserPop += '<ul>';
//formNewUserPop +='<li><a class="linkFB" data-controller-path="/linked_accounts/facebook/info" data-controller-action="GET" href="javascript:void(0)" onclick="checkLoginState(this, 'new_user_pop')"><i aria-hidden="true" class="fa fa-facebook"></i><span>Continue with Facebook</span></a></li>';
formNewUserPop += '</ul>';
formNewUserPop += '<div class="midStrip"><span>OR</span></div>';
formNewUserPop += '</div>';
formNewUserPop += '</div>';
formNewUserPop += '<div data-validate="presence" class="form-group">';
formNewUserPop += '<label for="user_first_name" class="control-label">First Name</label>';
formNewUserPop += '<input type="text" id="user_first_name" name="user[first_name]" size="30" class="form-control input-lg" maxlength="30">';
formNewUserPop += '<div style="color:#ff5c61;font-size:11pt" class="error-msg"><em><span>This is a required field</span></em></div></div>';
formNewUserPop += '<div data-validate="presence" class="form-group">';
formNewUserPop += '<label for="user_last_name" class="control-label">Last Name</label>';
formNewUserPop += '<input type="text" id="user_last_name" name="user[last_name]" size="30" class="form-control input-lg" maxlength="30">';
formNewUserPop += '</div>';
formNewUserPop += '<div data-validate="presence,email,emailUniqueness, emailValidTopLevelDomain, emailRareTopLevelDomain" class="form-group">';
formNewUserPop += '<label for="user_email" class="control-label">Email</label>';
formNewUserPop += '<input type="email" id="user_email" name="user[email]" size="75" class="form-control input-lg" maxlength="75">';
formNewUserPop += '</div>';
formNewUserPop += '<div data-validate="presence,zip" class="form-group" style="display: none;">';
formNewUserPop += '<label for="user_client_attributes_shipping_postcode" class="control-label">Zip Code</label>';
formNewUserPop += '<input type="hidden" id="user_client_attributes_shipping_postcode" name="user[client_attributes][shipping_postcode]" size="10" maxlength="10" class="form-control input-lg" value="94107">';
formNewUserPop += '<p class="instructional-note  inline-note">At this time we ship only to U.S. mailing addresses.</p>';
formNewUserPop += '</div>';
formNewUserPop += '<div class="form-group submission">';
formNewUserPop += '<p class="instructional-note">By signing up you accept the <a href="https://www.stitchfix.com/terms?utm_campaign=68ba126472fa2d9a8bb75a848dbd29cd&amp;utm_source=ampush&amp;utm_medium=other">terms and conditions</a> of Stitch&nbsp;Fix.</p>';
formNewUserPop += '<input type="submit" data-disable-with="Signing up..." class="btn btn-red btn-lg submit" value="Take Your Style Quiz" name="commit">';
formNewUserPop += '<div class="help-block">Already a member? <a href="https://www.stitchfix.com/login?utm_campaign=68ba126472fa2d9a8bb75a848dbd29cd&amp;utm_source=ampush&amp;utm_medium=other">Sign In »</a></div>';
formNewUserPop += '<div class="registration-opt-in">';
formNewUserPop += '<div class="email-opt-in">';
formNewUserPop += '<div class="checkbox small">';
formNewUserPop += '<input type="hidden" value="0" name="user[email_opt_in]">';
formNewUserPop += '<input type="checkbox" id="user_email_opt_in" name="user[email_opt_in]" checked="checked" value="1">';
formNewUserPop += '<label for="user_email_opt_in" class="control-label">Id like to receive exclusive news, styling tips and more</label>';
formNewUserPop += '</div>';
formNewUserPop += '</div>';
formNewUserPop += '</div>';
formNewUserPop += '</div>';
formNewUserPop += '</form>';


var sizecharts = "";
sizecharts +='<div class="row">';
sizecharts +='<div class="col-xs-12">';
sizecharts +='<section class="size-chart">';
sizecharts +='<h6>Weight (lbs.)</h6>';
sizecharts +='<table class="size-chart">';
sizecharts +='<thead>';
sizecharts +='<tr>';
sizecharts +='<th>&nbsp;</th>';
sizecharts +='<th class="">&lt; 100</th>';
sizecharts +='<th class="">110</th>';
sizecharts +='<th class="">120</th>';
sizecharts +='<th class="">130</th>';
sizecharts +='<th class="">140</th>';
sizecharts +='<th class="">150</th>';
sizecharts +='<th class="">160</th>';
sizecharts +='<th class="">170</th>';
sizecharts +='<th class="">180</th>';
sizecharts +='<th class="">190</th>';
sizecharts +='<th class="">200</th>';
sizecharts +='<th class="">200+</th>';
sizecharts +='</tr>';
sizecharts +='</thead>';
sizecharts +='<tbody>';
sizecharts +='<tr>';
sizecharts +='<td class="xs">XS</td>';
sizecharts +='<td class="s">S</td>';
sizecharts +='<td class="s">S</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="xl">XL</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='</tr>';
sizecharts +='<tr>';
sizecharts +='<th>5’0”</th>';
sizecharts +='<td class="xs">XS</td>';
sizecharts +='<td class="s">S</td>';
sizecharts +='<td class="s">S</td>';
sizecharts +='<td class="s">S</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="xl">XL</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='</tr>';
sizecharts +='<tr>';
sizecharts +='<th>5’1”</th>';
sizecharts +='<td class="xs">XS</td>';
sizecharts +='<td class="s">S</td>';
sizecharts +='<td class="s">S</td>';
sizecharts +='<td class="s">S</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="xl">XL</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='</tr>';
sizecharts +='<tr>';
sizecharts +='<th>5’2”</th>';
sizecharts +='<td class="xs">XS</td>';
sizecharts +='<td class="xs">XS</td>';
sizecharts +='<td class="s">S</td>';
sizecharts +='<td class="s">S</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="xl">XL</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='</tr>';
sizecharts +='<tr>';
sizecharts +='<th>5’3”</th>';
sizecharts +='<td class="xs">XS</td>';
sizecharts +='<td class="xs">XS</td>';
sizecharts +='<td class="s">S</td>';
sizecharts +='<td class="s">S</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="xl">XL</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='</tr>';
sizecharts +='<tr>';
sizecharts +='<th>5’4”</th>';
sizecharts +='<td class="xs">XS</td>';
sizecharts +='<td class="xs">XS</td>';
sizecharts +='<td class="s">S</td>';
sizecharts +='<td class="s">S</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="xl">XL</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='</tr>';
sizecharts +='<tr>';
sizecharts +='<th>5’5”</th>';
sizecharts +='<td class="xs">XS</td>';
sizecharts +='<td class="xs">XS</td>';
sizecharts +='<td class="s">S</td>';
sizecharts +='<td class="s">S</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="xl">XL</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='</tr>';
sizecharts +='<tr>';
sizecharts +='<th>5’6”</th>';
sizecharts +='<td class="xs">XS</td>';
sizecharts +='<td class="s">S</td>';
sizecharts +='<td class="s">S</td>';
sizecharts +='<td class="s">S</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="xl">XL</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='</tr>';
sizecharts +='<tr>';
sizecharts +='<th>5’7”</th>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="s">S</td>';
sizecharts +='<td class="s">S</td>';
sizecharts +='<td class="s">S</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="xl">XL</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='</tr>';
sizecharts +='<tr>';
sizecharts +='<th>5’8”</th>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="s">S</td>';
sizecharts +='<td class="s">S</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="xl">XL</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='</tr>';
sizecharts +='<tr>';
sizecharts +='<th>5’9”</th>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="s">S</td>';
sizecharts +='<td class="s">S</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="xl">XL</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='</tr>';
sizecharts +='<tr>';
sizecharts +='<th>5’10”</th>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="s">S</td>';
sizecharts +='<td class="s">S</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="xl">XL</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='</tr>';
sizecharts +='<tr>';
sizecharts +='<th>5’11”</th>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="xl">XL</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='</tr>';
sizecharts +='<tr>';
sizecharts +='<th>6’0”</th>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="xl">XL</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='</tr>';
sizecharts +='<tr>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="m">M</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="l">L</td>';
sizecharts +='<td class="xl">XL</td>';
sizecharts +='<td class="na">&nbsp;&nbsp;&nbsp;</td>';
sizecharts +='</tr>';
sizecharts +='</tbody>';
sizecharts +='</table>';
sizecharts +='<legend>Currently we are only able to style XS&thinsp;&ndash;&thinsp;XL (0&thinsp;&ndash;14)</legend>';
sizecharts +='</section>';
sizecharts +='</div>';
sizecharts +='</div>';


var showsm = '<div class="show-sm image-3"></div><div class="carousel-inner"></div><section class="copy"></section>';
var horizontal = '<div class="horizontal bg-sizing image-1"></div>';